# Docker Compose configuration for Mochi-Moo
# Author: Cazandra Aporbo MS

version: '3.8'

services:
  mochi-api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MOCHI_MODE=production
    volumes:
      - ./data:/app/data
      - ./.mochi_trace:/app/.mochi_trace
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
